server.port=8088

front.address=http://localhost:4200

spring.data.mongodb.database=happyhourfinder_mongodb
spring.data.mongodb.port=27017

management.endpoints.web.cors.allowed-origins=http://localhost:4200
management.endpoints.web.cors.allowed-methods=GET