kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  selector:
    app: ${PROJECT_NAME}
    tier: backend
  ports:
  - protocol: TCP
    port: 8088
    targetPort: http
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
        tier: backend
        track: stable
    spec:
      containers:
      - name: backend
        image: eu.gcr.io/${GOOGLE_PROJECT_ID}/${BACK_IMAGE_NAME}:${CIRCLE_SHA1}
        ports:
        - name: http
          containerPort: 8088
