version: 2.1

executors:
  executor-java:
    working_directory: /tmp/happy-hour-finder-server/backend
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          VERSION: 1.2.0-SNAPSHOT
          IMAGE_NAME: mathieuaime/happyhourfinder-backend
          MAVEN_OPTS: -Xmx3200m
      - image: circleci/mysql
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: happyhourfinder
  executor-node:
    working_directory: /tmp/happy-hour-finder-server/frontend
    docker:
      - image: circleci/node:10.7.0-browsers
    environment:
      VERSION: 1.2.0-SNAPSHOT
      IMAGE_NAME: mathieuaime/happyhourfinder-frontend
  executor-buildpack:
    working_directory: /tmp/happy-hour-finder-server/backend
    docker:
      - image: buildpack-deps:stretch

jobs:
  install_back:
    executor: executor-java
    steps:
      - checkout:
          path: /tmp/happy-hour-finder-server
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: mvn dependency:go-offline
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  integration_tests_back:
    executor: executor-java
    steps:
      - checkout:
          path: /tmp/happy-hour-finder-server
      - run:
          name: Integration tests
          command: mvn integration-test
      - run:
          name: Generate Code Coverage Report
          command: mvn org.jacoco:jacoco-maven-plugin:prepare-agent -Dmaven.test.failure.ignore=false
      - run:
          name: Run Code Quality Analysis
          command: mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=${CIRCLE_BRANCH}
      - store_artifacts:
          path: target/happy-hour-finder-backend-1.2.0-SNAPSHOT.jar
      - store_test_results:
          path: target/surefire-reports

  publish_back:
    executor: executor-java
    steps:
      - checkout:
          path: /tmp/happy-hour-finder-server
      - setup_remote_docker
      - run:
          name: Packaging
          command: mvn package -DskipTests
      - run:
          name: Build Docker Image
          command: docker build --build-arg JAR_FILE=target/happy-hour-finder-backend-$VERSION.jar -t $IMAGE_NAME:$VERSION .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$VERSION

  deploy_back:
    executor: executor-buildpack
    steps:
      - run:
          name: Deploying Back
          command: echo "Deploy !"

  build_front:
    executor: executor-node
    steps:
      - checkout:
          path: /tmp/happy-hour-finder-server
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install local dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Testing
          command: npm run test
      - run:
          name: Building
          command: npm run build
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  publish_front:
    executor: executor-node
    steps:
      - checkout:
          path: /tmp/happy-hour-finder-server
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:$VERSION .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$VERSION

  deploy_front:
    executor: executor-buildpack
    steps:
      - run:
          name: Deploying front
          command: echo "Deploy !"

workflows:
  version: 2
  build:
    jobs:
      - install_back
      - integration_tests_back:
          requires:
            - install_back
      - publish_back:
          requires:
            - integration_tests_back
          filters:
            branches:
              only:
                - master
                - dev
      - deploy_back:
          requires:
            - publish_back

      - build_front
      - publish_front:
          requires:
            - build_front
          filters:
            branches:
              only:
                - master
                - dev
                - DOCKER
      - deploy_front:
          requires:
            - publish_front
