version: 2.1

executors:
  executor-java:
    working_directory: /tmp/happy-hour-finder-server/backend
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          VERSION: 1.2.0-SNAPSHOT
          REPOSITORY: mathieuaime
          IMAGE_NAME: happyhourfinder-backend
          MAVEN_OPTS: -Xmx3200m
  executor-int:
    working_directory: /tmp/happy-hour-finder-server/backend
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          MAVEN_OPTS: -Xmx3200m
      - image: circleci/mysql
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: happyhourfinder
  executor-node:
    working_directory: /tmp/happy-hour-finder-server/frontend
    docker:
      - image: circleci/node:10.7.0-browsers
    environment:
      VERSION: 1.2.0-SNAPSHOT
      REPOSITORY: mathieuaime
      IMAGE_NAME: happyhourfinder-frontend
  executor-buildpack:
    working_directory: /tmp/happy-hour-finder-server/backend
    docker:
      - image: buildpack-deps:stretch
  executor-gcloud:
    docker:
      - image: google/cloud-sdk
    environment:
      GOOGLE_PROJECT_ID: happyhourfinder
      GOOGLE_CLUSTER_NAME: happyhourfinder-cluster
      PROJECT_NAME: happy-hour-finder
      BACK_IMAGE_NAME: happyhourfinder-backend
      FRONT_IMAGE_NAME: happyhourfinder-frontend

jobs:
  unit_tests_back:
    executor: executor-java
    steps:
      - checkout:
          path: /tmp/happy-hour-finder-server
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Unit tests
          command: mvn test -P unit-tests
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  integration_tests_back:
    executor: executor-int
    steps:
      - checkout:
          path: /tmp/happy-hour-finder-server
      - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "pom.xml" }}
                  - v1-dependencies-
      - run:
          name: Integration tests
          command: mvn integration-test
      - run:
          name: Generate Code Coverage Report
          command: mvn org.jacoco:jacoco-maven-plugin:prepare-agent -Dmaven.test.failure.ignore=false
      - run:
          name: Run Code Quality Analysis
          command: mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=${CIRCLE_BRANCH}
      - store_artifacts:
          path: target/happy-hour-finder-backend-1.2.0-SNAPSHOT.jar
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  publish_back:
    executor: executor-java
    steps:
      - checkout:
          path: /tmp/happy-hour-finder-server
      - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "pom.xml" }}
                  - v1-dependencies-
      - setup_remote_docker
      - run:
          name: Packaging
          command: mvn package -DskipTests
      - run:
          name: Build Docker Image
          command: docker build -t ${REPOSITORY}/$IMAGE_NAME:$VERSION .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push ${REPOSITORY}/$IMAGE_NAME:$VERSION
            docker tag ${REPOSITORY}/$IMAGE_NAME:$VERSION ${REPOSITORY}/$IMAGE_NAME:${CIRCLE_BRANCH}
            docker push ${REPOSITORY}/$IMAGE_NAME:${CIRCLE_BRANCH}

  deploy_back_to_staging:
    working_directory: /tmp/happy-hour-finder-server/backend
    executor: executor-gcloud
    steps:
      - checkout:
          path: /tmp/happy-hour-finder-server
      - run:
          name: Install tools
          command: |
            apt-get install -qq -y gettext maven
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - setup_remote_docker
      - restore_cache:
                keys:
                  - v1-dependencies-{{ checksum "pom.xml" }}
                  - v1-dependencies-
      - run:
          name: Packaging
          command: |
            mvn package -DskipTests
      - run:
          name: Docker build and push
          command: |
            docker build -t ${BACK_IMAGE_NAME} .
            docker tag ${BACK_IMAGE_NAME} eu.gcr.io/${GOOGLE_PROJECT_ID}/${BACK_IMAGE_NAME}:${CIRCLE_SHA1}
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io
            docker push eu.gcr.io/${GOOGLE_PROJECT_ID}/${BACK_IMAGE_NAME}:${CIRCLE_SHA1}
      - run:
          name: Deploy to Kubernetes
          command: |
            envsubst < /tmp/happy-hour-finder-server/backend/k8s.yml > /tmp/patched_k8s.yml
            kubectl apply -f /tmp/patched_k8s.yml
            kubectl rollout status deployment/backend
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  build_front:
    executor: executor-node
    steps:
      - checkout:
          path: /tmp/happy-hour-finder-server
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install local dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Testing
          command: npm run test
      - run:
          name: Building
          command: npm run build
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  publish_front:
    executor: executor-node
    steps:
      - checkout:
          path: /tmp/happy-hour-finder-server
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t ${REPOSITORY}/$IMAGE_NAME:$VERSION .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push ${REPOSITORY}/$IMAGE_NAME:$VERSION
            docker tag ${REPOSITORY}/$IMAGE_NAME:$VERSION ${REPOSITORY}/$IMAGE_NAME:${CIRCLE_BRANCH}
            docker push ${REPOSITORY}/$IMAGE_NAME:${CIRCLE_BRANCH}

  deploy_front_to_staging:
    working_directory: /tmp/happy-hour-finder-server/frontend
    executor: executor-gcloud
    steps:
      - checkout:
          path: /tmp/happy-hour-finder-server
      - run:
          name: Install tools
          command: |
            apt-get install -qq -y gettext
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - setup_remote_docker
      - run:
          name: Docker build and push
          command: |
            docker build -t ${FRONT_IMAGE_NAME} .
            docker tag ${FRONT_IMAGE_NAME} eu.gcr.io/${GOOGLE_PROJECT_ID}/${FRONT_IMAGE_NAME}:${CIRCLE_SHA1}
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io
            docker push eu.gcr.io/${GOOGLE_PROJECT_ID}/${FRONT_IMAGE_NAME}:${CIRCLE_SHA1}
      - run:
          name: Deploy to Kubernetes
          command: |
            envsubst < /tmp/happy-hour-finder-server/frontend/k8s.yml > /tmp/patched_k8s.yml
            kubectl apply -f /tmp/patched_k8s.yml
            kubectl rollout status deployment/frontend

workflows:
  version: 2
  backend:
    jobs:
      - unit_tests_back
      - integration_tests_back
      - publish_back:
          requires:
            - unit_tests_back
            - integration_tests_back
          filters:
            branches:
              only:
                - master
                - dev
      - deploy_back_to_staging:
          requires:
            - unit_tests_back
          filters:
            branches:
              only:
                - master
                - dev
                - GKE
  frontend:
    jobs:
      - build_front
      - publish_front:
          requires:
            - build_front
          filters:
            branches:
              only:
                - master
                - dev
      - deploy_front_to_staging:
          requires:
            - build_front
          filters:
            branches:
              only:
                - master
                - dev
                - GKE