# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build_back:
    working_directory: ~/happy-hour-finder-server/backend

    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          MAVEN_OPTS: -Xmx3200m

      - image: circleci/mysql
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: happyhourfinder

    steps:
      - checkout:
          path: ~/happy-hour-finder-server

      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: mvn dependency:go-offline

      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run:
          name: Integration tests
          command: mvn integration-test

      - run:
          name: Checkstyle
          command: mvn checkstyle:checkstyle

      - run:
          name: Generate Code Coverage Report
          command: mvn org.jacoco:jacoco-maven-plugin:prepare-agent -Dmaven.test.failure.ignore=false

      - run:
          name: Run Code Quality Analysis
          command: mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=${CIRCLE_BRANCH}

      - run:
          name: Packaging
          command: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/happy-hour-finder-backend-1.1.0.jar

  build_front:
    working_directory: ~/happy-hour-finder-server/frontend

    docker:
      - image: circleci/node:10.7.0-browsers

    steps:
      - checkout:
          path: ~/happy-hour-finder-server

      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install local dependencies
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Testing
          command: npm run test

      - run:
          name: Building
          command: npm run build

      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

      - store_artifacts:
          path: target/happy-hour-finder-frontend-1.1.0.jar

workflows:
  version: 2

  build:
    jobs:
      - build_back
      - build_front
