server.port=8088

front.address=http://frontend:4200

spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://mysql_db:3306/happyhourfinder
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=false

management.endpoints.web.cors.allowed-origins=http://frontend:4200
management.endpoints.web.cors.allowed-methods=GET